model_name: 'cosmos2_train'
is_i2v: True
report_to: None
tracker_name: cosmos2_trainer
output_dir: outputs/cosmos2_train   # 训练产出目录（ckpt/日志）

logging_dir: logs

train_data_class_path: data/agibotworld_dataset.py   # 数据集类路径，例如 data/agibotworld_dataset.py
train_data_class: AgiBotWorld              # 训练集类名
val_data_class_path: data/agibotworld_dataset.py  # 验证集类路径，若同训练集可复用
val_data_class: AgiBotWorld          # 验证集类名，若同训练集可复用

pretrained_model_name_or_path: /workspace/Cosmos-Predict2-2B-Video2World
tokenizer_pretrained_model_name_or_path: /workspace/Cosmos-Predict2-2B-Video2World


### 
tokenizer_class_path: transformers
tokenizer_class: T5TokenizerFast
textenc_class_path: transformers
textenc_class: T5EncoderModel

vae_class_path: models/cosmos_models/models/autoencoders/autoencoder_kl_wan.py
vae_class: AutoencoderKLWan

diffusion_model_class_path: models/cosmos_models/models/transformers/transformer_cosmos_multiview.py
diffusion_model_class: MultiViewCosmosTransformer3DModel

diffusion_scheduler_class_path: models/pipeline/gesim_cosmos2_pipeline_utils/scheduling_flow_match_euler_discrete.py
diffusion_scheduler_class: FlowMatchEulerDiscreteScheduler 

pipeline_class_path: models/pipeline/gesim_pipeline.py
pipeline_class: GeSimCosmos2Pipeline


# 
return_action: false
return_video: true
action_loss_scale: 1.0
action_cond_mode: true
train_mode: 'video_only'

mixed_precision: bf16
allow_tf32: False

caption_dropout_p: 0.06

# dataloader
batch_size: 4
dataloader_num_workers: 1

gradient_checkpointing: True
noise_to_first_frame: 0.1


max_grad_norm: 1.0
gradient_accumulation_steps: 1

# Optimizer Config
optimizer: adamw
lr: 3e-5                      # TODO: 根据显存/任务调节
beta1: 0.9
beta2: 0.95
beta3: 0.999
epsilon: 1e-8
weight_decay: 1e-5
optimizer_8bit: False
optimizer_torchao: False
scale_lr: False

# lr_scheduler Config
lr_scheduler: constant_with_warmup
lr_warmup_steps: 1000
lr_num_cycles: 1
lr_power: 1.0

# Timestep Config
flow_weighting_scheme: none
flow_logit_mean: 0.0
flow_logit_std: 1.0
flow_mode_scale: 1.29

# 训练/日志/验证/保存步数
train_steps: 1000000 # 总步数
train_epochs: 10000 # 总epoch数
steps_to_save: 500 # 每多少步保存一次
steps_to_log: 20 # 每多少步记录一次日志
steps_to_val: 500 # 每多少步验证一次

# timeout, seconds
nccl_timeout: 600
seed: 42

# vae
enable_slicing: True
enable_tiling: True


# Timestep Config
flow_weighting_scheme: none
flow_logit_mean: 0.0
flow_logit_std: 1.0
flow_mode_scale: 1.29

pixel_wise_timestep: False


diffusion_model:
  model_path: /workspace/Genie-Envisioner/models/ge_sim_cosmos_v0.1.safetensors

  config:
    in_channels: 26  # 16 (vae) + 3 (traj) + 6 (raymap) + 1 (padding mask)
    out_channels: 16
    num_attention_heads: 16
    attention_head_dim: 128
    num_layers: 28
    mlp_ratio: 4.0
    text_embed_dim: 1024
    adaln_lora_dim: 256
    max_size: [128, 240, 240]
    patch_size: [1, 2, 2]
    rope_scale: [1.0, 3.0, 3.0]
    concat_padding_mask: true  # TODO: no idea how does this work
    extra_pos_embed_type: null
    use_view_embed: true
    action_expert: false
    action_in_channels: 7
    action_num_attention_heads: 16
    action_attention_head_dim: 32
    action_rope_dim: 32


data:
  train:
    data_roots: ["/workspace/AgiBotWorld-Alpha"]
    task_info_root: "/workspace/AgiBotWorld-Alpha/task_info"
    domains: ["agibotworld", ]
    specific_tasks: [327, ] # 指定任务id
    dataset_info_cache_path: "/workspace/Genie-Envisioner/outputs/save/train/dataset_meta_info_cache"
    previous_pick_mode: 'random'
    sample_size: [384, 512]
    sample_n_frames: 360
    preprocess :  'resize'
    valid_cam :  ['head', 'hand_left', 'hand_right']
    # GE-Sim 条件训练需要 eef_quat（xyz+quat+gripper）来生成 traj map
    action_space: "eef_quat"
    action_type: "absolute"
    chunk: 25 ### 4n+1 for cosmos without padding frames
    action_chunk: 25
    n_previous: 4
  val:
    data_roots: ["/workspace/AgiBotWorld-Alpha"]
    task_info_root: "/workspace/AgiBotWorld-Alpha/task_info"
    domains: ["agibotworld", ]
    specific_tasks: [327, ] # 指定任务id
    dataset_info_cache_path: "/workspace/Genie-Envisioner/outputs/save/train/dataset_meta_info_cache"
    previous_pick_mode: 'random'
    sample_size: [384, 512]
    sample_n_frames: 360
    preprocess :  'resize'
    valid_cam :  ['head', 'hand_left', 'hand_right']
    action_space: "eef_quat"
    action_type: "absolute"
    chunk: 25
    action_chunk: 25
    n_previous: 4

use_color_jitter: true
num_inference_step: 15

load_weights: true

data_root: /workspace/AgiBotWorld-Alpha
task_id: 327
episode_id: 648642